import { ISetting, SettingType } from '@rocket.chat/apps-engine/definition/settings';

export const settings: Array<ISetting> = [
    {
        id: 'jira-url',
        type: SettingType.STRING,
        packageValue: '',
        required: true,
        public: true,
        i18nLabel: 'Jira base URL',
        i18nDescription: 'Base URL of your Jira instance, e.g. https://jira.example.ch',
        i18nPlaceholder: 'https://jira.example.ch',
    },
    {
        id: 'jira-user',
        type: SettingType.STRING,
        packageValue: '',
        required: true,
        public: false,
        i18nLabel: 'Jira username',
        i18nDescription: 'User the app authenticates as. Needs "Browse Projects" permission on the projects it should resolve.',
    },
    {
        id: 'jira-token',
        type: SettingType.PASSWORD,
        packageValue: '',
        required: true,
        public: false,
        i18nLabel: 'Jira token',
        i18nDescription: 'Personal access token (PAT) or API token, depending on the auth mode setting below.',
    },
    {
        id: 'jira-auth-mode',
        type: SettingType.SELECT,
        packageValue: 'pat',
        required: true,
        public: true,
        values: [
            { key: 'pat', i18nLabel: 'Bearer token (personal access token)' },
            { key: 'basic', i18nLabel: 'Basic auth (username + API token as password)' },
        ],
        i18nLabel: 'Jira auth mode',
        i18nDescription: 'Jira Server/Data Center PATs are validated with Bearer auth. Use Basic only if your instance requires it.',
    },
    {
        id: 'issue-pattern',
        type: SettingType.STRING,
        packageValue: '\\b[A-Z][A-Z0-9]{1,20}-\\d+\\b',
        required: false,
        public: true,
        i18nLabel: 'Issue key pattern',
        i18nDescription: 'Regular expression matching Jira issue keys in messages.',
    },
    {
        id: 'project-keys',
        type: SettingType.STRING,
        packageValue: '',
        required: false,
        public: true,
        i18nLabel: 'Project key allowlist',
        i18nDescription: 'Optional comma-separated list of Jira project keys to rewrite (e.g. SALES,SUPPORT). Empty means all projects.',
    },
    {
        id: 'abbrev-length',
        type: SettingType.NUMBER,
        packageValue: 40,
        required: false,
        public: true,
        i18nLabel: 'Maximum summary length',
        i18nDescription: 'Maximum number of characters of the issue summary shown inside the link text.',
    },
    {
        id: 'ignore-users',
        type: SettingType.STRING,
        packageValue: '',
        required: false,
        public: true,
        i18nLabel: 'Ignored usernames',
        i18nDescription: 'Optional comma-separated list of usernames whose messages are never rewritten.',
    },
];
